server:
  port: 8080
spring:
  application:
    name: trb-loans
  datasource:
    url: jdbc:postgresql://trb-loans-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: migrations