server:
  port: 8080
spring:
  application:
    name: trb-loans
  datasource:
    url: jdbc:postgresql://trb-loans-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: migrations
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    loan-repayment: "transaction.loan-repayment"
    loan-payment: "transaction.loan-payment"
    loan-repayment-callback: "transaction.loan-repayment-callback"

urls:
  core: ${CORE_URL}
  users: ${USERS_URL}

scheduler:
  loan-repayment-send-transaction: "0 0 18 * * *"
  loan-repayment-update-status: "0 0 */6 * * *"
  loan-repayment-calculate-penny: "0 0 1 * * *"