server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/trb-loans
    username: trb-loans
    password: trb-loans
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9000,localhost:9001

urls:
  core: http://localhost:8080/
  users: http://localhost:8082/

scheduler:
  loan-repayment-send-transaction: "1 * * * * *"
  loan-repayment-calculate-penny: "1 * * * * *"
  loan-repayment-update-status: "1 * * * * *"
